apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/ibrahimmalii/k8s.git'
    targetRevision: HEAD
    directory:
      jsonnet:
        tlas:
          - {}
  sources: []
  project: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
